#!/usr/bin/env ruby

sinks = `pactl list sinks short`
    .split("\n")
    .map { |line| line.split("\t") }
current_sink_name = `pactl info`
    .split("\n")
    .filter { |line| line.include? "Default Sink" }
    .first["Default Sink: ".length()..]
index = sinks.find_index { |line| line.include? current_sink_name }
next_sink = sinks[(index + 1) % sinks.length()][0]
`pactl set-default-sink #{next_sink}`
