#!/bin/bash

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/bin:$PATH"

# Rust
export PATH="$HOME/.cargo/bin:$PATH"

# Go
export GOPATH="$HOME/code/go"
export PATH="$PATH:$GOPATH/bin"

# Perl
export PATH="$HOME/.perl5/bin:$PATH"
export PERL5LIB="$HOME/.perl5/lib/perl5:$PERL5LIB"
export PERL_LOCAL_LIB_ROOT="$HOME/.perl5:$PERL_LOCAL_LIB_ROOT"
export PERL_MB_OPT="--install_base \"$HOME/.perl5\""
export PERL_MM_OPT="INSTALL_BASE=$HOME/.perl5"
