#!/usr/bin/env bash

if [ -z "$SWAYSOCK" ]; then
    echo 'Sway not detected'
    exit 1
fi

$@ &
pid=$!
id=""

while [ -z $id ]; do
    id=$(swaymsg -t subscribe '[ "window" ]' | jq --argjson pid "$pid" '.container | select(.pid == $pid) | .id')
done

swaymsg [ con_id=$id ] floating enable
