set -xg fish_color_autosuggestion brblack
set -xg fish_color_cancel black
set -xg fish_color_command blue
set -xg fish_color_comment brblack
set -xg fish_color_cwd green
set -xg fish_color_cwd_root green
set -xg fish_color_end brblack
set -xg fish_color_error brred
set -xg fish_color_escape brblue
set -xg fish_color_history_current --bold
set -xg fish_color_host purple
set -xg fish_color_match --background=brblue
set -xg fish_color_normal black
set -xg fish_color_operator black
set -xg fish_color_param bryellow
set -xg fish_color_quote green
set -xg fish_color_redirection brblue
set -xg fish_color_search_match yellow
set -xg fish_color_selection 'black'  '--background=brwhite'
set -xg fish_color_status red
set -xg fish_color_user yellow
set -xg fish_color_valid_path --underline
set -xg fish_color_vcs bryellow
