#! /bin/sh

dow=$(date +%u)
case $dow in
    1) col=red ;;
    2) col=orange ;;
    3) col=yellow ;;
    4) col=green ;;
    5) col=blue ;;
    6) col=pink ;;
    7) col=white ;;
esac

swaybg -i ~/.config/sway/desktop/$col.jpg -m fill &
